### ISSUE TITLE
Optional AI pathing mode (or separate lower-tier ocarina) that eschews teleportation

### ISSUE THREAD

**Issue by noobanidus** [noobanidus/dwmh#6]
This would simply set the player as the destination and begin horses pathing towards that destination. This would be problematic in instances where horses have become stuck (i.e., fell down a ravine).

**Comment by duely** [comment]
See the pathing branch and the following images for current difficulties:

![](https://thumbs.gfycat.com/WelcomeDeficientAlpineroadguidetigerbeetle-size_restricted.gif)

![](https://thumbs.gfycat.com/EagerHandsomeAcornbarnacle-size_restricted.gif)

**Comment by duely** [comment]
I recall know that Tschipp's mod Callable Horse actually does this in a sane manner involving considerably less brute-forcing of AI and navigator. I need to look into it more because it should still be an option.
