### ISSUE TITLE
Whitelist/Blacklist for summonable mobs

### ISSUE THREAD

**Issue by inkdear** [noobanidus/dwmh#91]
Yeah, basically just what it says in the title. In my case, I want to limit the summoning to pretty much exclusively steeds and pets, not just any livestock, wild animal etc (thus a use for a whitelist), but the more pressing issue is stuff like it being possible to summon untamed dragons (among other creatures) from Ice and Fire, potentially teleporting them into killrooms.  It'd be great if the player were able to restrict which entities are summonable.

**Comment by duely** [comment]
Sure, this is doable! I'll try to have a release out with it included soon.

**Comment by inkdear** [comment]
Awesome! Thanks so much!
