### ISSUE TITLE
When a tracked mob dies there is no way to untrack it after death. 

### ISSUE THREAD

**Issue by HogPilot01** [noobanidus/dwmh#98]
When I was testing out the mod for a modpack I am making, I noticed that if you summon a tracked mob and it dies of fall damage or lava, it sends the mob into a loop where it is summoned and dies the moment it touches solid ground. Relogging does not help either as it just says that it cannot find the Entity to summon.

Maybe make Shift+Left Click untrack an entity will fix this issue.

**Comment by noobanidus** [comment]
Just to clarify, is this for 1.14.4 or 1.12.2?

**Comment by HogPilot01** [comment]
This is the 1.12 version.
