### ISSUE TITLE
Entity Duplication on version 1.12.2

### ISSUE THREAD

**Issue by TheJessaChannel** [noobanidus/dwmh#99]
1.12.2 - Forge 2847 - dwmh-1.12.2-3.1.2.jar

When an entity is relatively far away, and I whistle, the entity is duplicated from time to time. So now I have three Dogs:

https://i.imgur.com/ia15b5Z.png

https://i.imgur.com/T6pcWeU.png

The only way to fix this is to kill the dogs and get a new one. :-(

**Comment by noobanidus** [comment]
That is pretty strange. I'm so much more inclined to just back-port "destructively" to single-entity without the entity-saving that 1.12.2 uses, as it's so much less reliable than just chunk-loading...

**Comment by TheJessaChannel** [comment]
It seems to be the same exact problem that this user had: https://github.com/noobanidus/dwmh/issues/97

It happened with me and several other players in our server. I am really bummed about this because this whistle works so much better than the whistle that comes with Doggy Talents and works on any entity. I wonder... does it work on boats, too? Hmm... I am constantly forgetting my boat.

So, any hope for a fix?

**Comment by noobanidus** [comment]
It appears to be only an issue with Doggy Talents? There might be some weird conflict.

**Comment by TheJessaChannel** [comment]
https://github.com/noobanidus/dwmh/issues/97

It is not just an issue with doggy Talents, it happens with any entity.

It is the same issue as issue 97:

> Both entity are considered the same: if i claime one, both are claimed, but only the summoned one is teleported, the same when trying to unclame one.

> If i unclame both, than kill the summoned one and claim back the original, trying to summon the original will result in an "unable to find the entity" message.

This is the exact behavior I am having.

Could you please put in a fix?

**Comment by noobanidus** [comment]
> Could you please put in a fix?

I'm sorry, but I have a lot of projects and commitments that I've already made. I will put a fix in, but it's not something I can do immediately, and most likely the fix will be back-porting the 1.14 and 1.15 systems which only allow a single entity per ocarina.
